version: '3'


services:
    webserver:
        image: nginx:alpine
        volumes:
            - ./:/var/www
                ## copy nginx configuration for our application ##
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        ports:
            ## run the webserver on port 8080 ##
            - '8001:80'
    
    mysql:
        image: mysql:5.7.29
        container_name: mysql_laravel
        restart: unless-stopped
        ports: 
            - "9306:3306"
        environment: 
            MYSQL_DATABASE: phpunit_laravel
            MYSQL_USER: root
            MYSQL_PASSWORD: pedro0605
            MYSQL_ROOT_PASSWORD: pedro0605
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks: 
            laravel:
                ipv4_address: 172.20.0.10

        volumes: 
            - ./mysql:/var/lib/mysql

    php:
        build: 
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: php_laravel
        volumes: 
            - ./:/var/www
        networks: 
            - laravel
        working_dir: /var/www
networks:
    laravel:
        ipam:
            driver: default
            config:
                - subnet: 172.20.0.0/16