version: '3'

networks:
  laravel:


services:
    webserver:
        image: nginx:alpine
        volumes:
            - ./:/var/www
                ## copy nginx configuration for our application ##
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/

    
    mysql:
        image: mysql:5.7.29
        container_name: mysql_laravel
        restart: unless-stopped
        ports: 
            - "9306:3306"
        environment: 
            MYSQL_DATABASE: phpunit_laravel
            MYSQL_USER: root
            MYSQL_PASSWORD: pedro0605
            MYSQL_ROOT_PASSWORD: pedro0605
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks: 
            - laravel
        volumes: 
            - ./mysql:/var/lib/mysql

    php:
        build: 
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: php_laravel
        volumes: 
            - ./:/var/www
        ports: 
            - "9004:9004"
        networks: 
            - laravel
        working_dir: /var/www

