version: '3'

networks:
  laravel:


services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx_laravel
        ports:
            - "7000:89"
        volumes:
            - ./src:/var/www/html
                ## copy nginx configuration for our application ##
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - php
            - mysql
        networks:
            laravel

    mysql:
        image: mysql:8.0
        container_name: mysql_laravel
        restart: unless-stopped
        ports: 
            - "9306:3306"
        environment: 
            MYSQL_DATABASE: phpunit_laravel
            MYSQL_USER: root
            MYSQL_PASSWORD: pedro0605
            MYSQL_ROOT_PASSWORD: pedro0605
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks: 
            - laravel
        volumes: 
            - ./mysql:/var/lib/mysql

    php:
        build: 
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: php_laravel
        volumes: 
            - ./src:/var/www/html
        ports: 
            - "9004:9004"
        networks: 
            - laravel
    
    composer:
        image: composer:latest
        container_name: composer_laravel
        volumes: 
            - ./src:/var/www/html
        working_dir: /var/www/html
        depends_on: 
            - php
        networks: 
            - laravel